### ISSUE TITLE
can't create Thread

### ISSUE THREAD

**Issue by jaimeiniesta** [obfusk/open_uri_w_redirect_to_https#1]
Hi, I get this when running the specs on OSX Mavericks, with ruby 2.1.3:

``` ruby
➔ rspec spec
............F

Failures:

  1) open w/ threads works
     Failure/Error: Thread.new {
     ThreadError:
       can't create Thread: Resource temporarily unavailable
     # ./spec/open_uri_w_redirect_to_https__spec.rb:161:in `initialize'
     # ./spec/open_uri_w_redirect_to_https__spec.rb:161:in `new'
     # ./spec/open_uri_w_redirect_to_https__spec.rb:161:in `block (4 levels) in <top (required)>'
     # ./spec/open_uri_w_redirect_to_https__spec.rb:118:in `times'
     # ./spec/open_uri_w_redirect_to_https__spec.rb:118:in `block (3 levels) in <top (required)>'

Finished in 24.79 seconds (files took 0.23313 seconds to load)
13 examples, 1 failure

Failed examples:

rspec ./spec/open_uri_w_redirect_to_https__spec.rb:116 # open w/ threads works
```

**Comment by obfusk** [comment]
Thanks. I guess 8000 threads is quite a lot ;-) It works just fine on Debian w/ ruby 2.1.4.

Unfortunately, I had to use `1000.times` to get your gem to fail reasonably consistently. So I don't really want to use a lower number here. I'll try to figure out a way to make it fail with fewer threads.

It would be interesting to know what the OSX maximum is. Could you maybe slowly lower the number to see how many are OK?

\- Felix

**Comment by jaimeiniesta** [comment]
I will. What's strange is that the spec you supplied on
open_uri_redirections doesn't have this problem.

**Comment by obfusk** [comment]
Actually, it isn't that strange since the other spec only creates 4000 threads (b/c it has fewer tests).

\- Felix

**Comment by obfusk** [comment]
The number of threads is now 10x less, like the improved failing spec for your gem. I assume OSX lets you run the spec now ;-) I've also modified the implementation to use thread variables instead of `caller`.

\- Felix

**Comment by jaimeiniesta** [comment]
Cool, now the specs pass on my mac.
